//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Extract()
        {
            this.Servis = new HashSet<Servis>();
        }
    
        public int Id { get; set; }
        public string Servise { get; set; }
        public string price { get; set; }
        public string With_privilege { get; set; }
        public Nullable<int> id_renter { get; set; }
        public int RenterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }
        public virtual Renter Renter { get; set; }
    }
}
