//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARMdatabaseEntities : DbContext
    {
        public ARMdatabaseEntities()
            : base("name=ARMdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Extract> Extracts { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Renter> Renters { get; set; }
        public virtual DbSet<Servis> Servises { get; set; }
    }
}
