//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Procent { get; set; }
        public Nullable<int> id_renter { get; set; }
        public int RenterId { get; set; }
    
        public virtual Renter Renter { get; set; }
    }
}
